# Generated by Django 4.2.1 on 2023-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
